name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file development/Dockerfile --tag file-explorer-backend:latest --target=dev\

      push:
        registry: hub.docker.com
        repository: ${{ secrets.DOCKER_USERNAME }}/file-explorer-backend
        tag: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
